### ISSUE TITLE
Storybook: Mock static query

### ISSUE THREAD

**Issue by asia-t** [ertrzyiks/yummy#129]
StaticQueries are not supported in Storybook out of the box, see e.g. Navbar stories.

There seem to be at least 2 ways to get around that:

1. Use the already generated files from public as proposed here:
https://github.com/gatsbyjs/gatsby/issues/12007#issuecomment-467730610

2. Mock gatsby and graphql:
https://www.gatsbyjs.org/docs/unit-testing/#3-useful-mocks-to-complete-your-testing-environment

**Comment by ertrzyiks** [comment]
Fixed by not using StaticQuery in storybook
