### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by ertrzyiks** [ertrzyiks/yummy#4]
We need yummy logo

**Comment by zuuritaly** [comment]
Hello @ertrzyiks 
I'm a graphic designer and I design logos for open source projects. I only create logos for projects that have a license, do you have one?

Usually I ask the following questions to assist me in the creative process:

Do you have something in your mind for the logo?
Do you want something specific for the logo?
What colors do you want in the logo?

With your answers I will design a logo for your project and if you like it you can keep it and used.

Best Regards

Zuur

**Comment by zuuritaly** [comment]
Hello @ertrzyiks!

With the informations that you give Im going to start the design of the logo, please add a license to a project.

Best regards!

Zuur

**Comment by ertrzyiks** [comment]
Hey @zuuritaly, that's great logo 👍 I like it and can't wait to put it on the blog. Thanks man

Could you send me as an SVG file, either here, with a Pull Request or to my email: 
mateusz.derks at gmail.com

I would put a separate license for the logo, some Creative Commons or whatever fits you to protect your copyright.

Please drop a line where I can send a donation / a beer / a chocolate!

**Comment by ertrzyiks** [comment]
![giphy](https://user-images.githubusercontent.com/2437969/42127257-15c2374a-7c95-11e8-90f7-b467ca5c229f.gif)
