### ISSUE TITLE
Tags containing Polish special characters are not parsed correctly

### ISSUE THREAD

**Issue by asia-t** [ertrzyiks/yummy#48]
Example url (that's how it's been copied from the address bar):
http://localhost:8000/tag/wegetaria%C5%84skie

This results in a crash:
<img width="662" alt="screen shot 2019-03-01 at 16 10 50" src="https://user-images.githubusercontent.com/14003958/53646885-9a8ac200-3c3c-11e9-9080-201517a8e63c.png">

**Comment by ertrzyiks** [comment]
Thanks for finding and reporting 👍 Fixed
